version: "3.9"
services:
  #Mandatory
  nginx:
    build: ./requirements/nginx
    volumes:
     - websites:/var/www/html
    ports:
      - "443:443"
    networks:
      - nginx-fpm
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    depends_on:
      - mariadb
      - wordpress
      - static_web

  wordpress:
    build: ./requirements/wordpress
    volumes:
     - websites:/var/www/html
    networks:
      - nginx-fpm
      - fpm-db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}
      WP_DB_NAME: ${WP_DB_NAME}
    restart: always
    depends_on:
      - mariadb
      - redis

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - fpm-db
    restart: always
    environment:
      MYSQL_ROOT_PW: ${MYSQL_ROOT_PW}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}
      WP_DB_NAME: ${WP_DB_NAME}

  #BONUS
  redis:
    build: ./requirements/bonus/redis
    networks:
      - fpm-db
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    volumes:
     - websites:/var/www/html
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    restart: always
    depends_on:
      - wordpress
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}

  adminer:
    build: ./requirements/bonus/adminer
    networks:
      - fpm-db
      - nginx-fpm
    volumes:
      - websites:/var/www/html
    restart: always
    depends_on:
      - wordpress
    
  portainer:
    build: ./requirements/bonus/portainer
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  static_web:
    build: ./requirements/bonus/static_web
    volumes:
      - websites:/var/www/html

# Networks definition
networks:
  nginx-fpm:
  fpm-db:

# Volumes configuration
volumes:
  websites:
    driver_opts:
      type: none
      device: /home/pmira-pe/data/websites/${WP_DB_NAME}
      o: bind
  db:
    driver_opts:
      type: none
      device: /home/pmira-pe/data/mariadb/${WP_DB_NAME}
      o: bind