version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
   #volumes:
   #  - websites:/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "nginx-wp"
    restart: always

  wordpress:
    build: ./requirements/wordpress
    #volumes:
    #  - websites:/
      #- wordpress:/var/www/html
    networks:
      - nginx-wp
      - wp-db
    expose:
      - "9000:9000"
    depends_on:
      - mariadb
      - nginx
    restart: always

  mariadb:
    build: ./requirements/mariadb
#    volumes:
#      - mysqldb:/var/run/mysql
    networks:
      - wp-db
#      - db:/var/lib/mysql
    expose:
     - "3306:3306"
    restart: always

#volumes:
#  websites:
#  mysqldb:
networks:
  nginx-wp:
  wp-db: