version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-wp
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    depends_on:
      - mariadb
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html
    networks:
      - nginx-wp
      - wp-db
    ports:
      - "9000:9000"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}
      WP_DB_NAME: ${WP_DB_NAME}
    restart: always

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - /home/pmira-pe/data/mariadb:/var/run/mysql
    networks:
      - wp-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PW: ${MYSQL_ROOT_PW}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}
      WP_DB_NAME: ${WP_DB_NAME}

networks:
  nginx-wp:
  wp-db: