version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-wp
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    depends_on:
      - mariadb
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html
    networks:
      - nginx-wp
      - wp-db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}
      WP_DB_NAME: ${WP_DB_NAME}
    restart: always
    depends_on:
      - mariadb
      - redis

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - /home/pmira-pe/data/mariadb/${WP_DB_NAME}:/var/lib/mysql
    networks:
      - wp-db
    restart: always
    environment:
      MYSQL_ROOT_PW: ${MYSQL_ROOT_PW}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}
      WP_DB_NAME: ${WP_DB_NAME}

  #BONUS
  redis:
    build: ./requirements/bonus/redis
    #volumes:?
    networks:
      - wp-db
    restart: always

  #ftp:
  #  build: ./requirements/bonus/ftp
  #  #volumes:
  #  #  - /home/pmira-pe/data/wordpress/${WP_DB_NAME}:?
  #  ports:
  #  - "21:21"
  #  - "21000-21010:21000-21010"
  #  restart: always
  #  #environment:
      
    

networks:
  nginx-wp:
  wp-db: