version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-wp
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    depends_on:
      - mariadb
      - wordpress
      - static_web

  wordpress:
    build: ./requirements/wordpress
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html
    networks:
      - nginx-wp
      - wp-db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}
      WP_DB_NAME: ${WP_DB_NAME}
    restart: always
    depends_on:
      - mariadb
      - redis

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - /home/pmira-pe/data/mariadb/${WP_DB_NAME}:/var/lib/mysql
    networks:
      - wp-db
    restart: always
    environment:
      MYSQL_ROOT_PW: ${MYSQL_ROOT_PW}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}
      WP_DB_NAME: ${WP_DB_NAME}

  #BONUS
  redis:
    build: ./requirements/bonus/redis
    networks:
      - wp-db
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html
    ports:
    - "20:20"
    - "21:21"
    - "21100-21110:21100-21110"
    restart: always
    depends_on:
     - wordpress

  adminer:
    build: ./requirements/bonus/adminer
    networks:
      - wp-db
      - nginx-wp
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html
    restart: always
    depends_on:
      - wordpress
    
  portainer:
    image: portainer/portainer:1.25.0-alpine
    ports:
      - "9000:9000"
    restart: always

  static_web:
    build: ./requirements/bonus/static_web
    volumes:
     - /home/pmira-pe/data/websites:/var/www/html


networks:
  nginx-wp:
  wp-db: